project:
  type: website
  output-dir: docs

website:
  title: "Talia Chait"
  navbar:
    background: primary
    right:
        - href: index.qmd
          text: Home
        - projects.qmd
        - posts.qmd
        - icon: twitter
          href: https://twitter.com/tchait_
        - icon: github
          href: https://github.com/tch8
    search: true
  page-footer:
    left:
      | 
      &copy; Talia Chait, 2023<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/) 
      | 
      Site built with <a href='https://quarto.org/'>Quarto</a> 

    right: 
      - icon: twitter
        href: https://twitter.com/tchait_
      - icon: github
        href: https://github.com/tch8
      
format:
  html:
    theme: sandstone
    css: styles.css
    toc: true

editor: visual

