project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"

website:
  title: "Talia Chait"
  navbar:
    left:
        - href: index.qmd
          text: Home
        - href: projects.qmd
          text: Projects
        - href: posts.qmd
          text: Posts
    right:
        - icon: linkedin
          href: https://www.linkedin.com/in/talia-chait-147464204/ 
        - icon: twitter
          href: https://twitter.com/tchait_
        - icon: github
          href: https://github.com/tch8
    search: true
    
  page-footer:
    left: | 
      &copy; Talia Chait, 2025<br>
      All content licensed under <i class='bi-badge-cc'></i>
      [(CC BY-NC-SA 4.0)](http://creativecommons.org/licenses/by-nc-sa/4.0/) 
      
    right: |
      Site built with <a href='https://quarto.org/'>Quarto</a> 
      
format:
  html:
    theme: [yeti, theme.scss]
    toc: true

editor: visual